import shutil
import subprocess
import sys
from pathlib import Path

import yaml
from langchain_core.runnables import RunnableConfig
from rich.console import Console

from cortexdocs.agents.state import DocPage, DocPlan, PipelineState
from cortexdocs.config import Settings
from cortexdocs.render.machine_artifacts import write_api_json, write_llms_full_txt, write_llms_txt

console = Console()


def render_node(state: PipelineState, config: RunnableConfig) -> dict:
    settings: Settings = config["configurable"]["settings"]
    manifest = state["manifest"]
    approved_pages: list[DocPage] = state["approved_pages"]
    doc_plan: DocPlan = state["doc_plan"]

    console.print(f"\n[bold]Render:[/bold] {len(approved_pages)} approved pages")

    # 1. Write machine artifacts
    console.print("  Writing machine artifacts...")
    write_api_json(manifest, approved_pages, settings.output_dir)
    write_llms_txt(manifest, approved_pages, settings.output_dir)
    write_llms_full_txt(approved_pages, settings.output_dir)
    console.print("  [green]✓[/green] api.json, llms.txt, llms-full.txt")

    # 2. Write MkDocs source
    site_src = settings.output_dir / "site_src"
    docs_dir = site_src / "docs"
    _prepare_docs_dir(docs_dir, approved_pages, manifest.server_name)

    # 3. Write mkdocs.yml
    mkdocs_yml_path = settings.output_dir / "mkdocs.yml"
    nav = _build_nav(doc_plan, approved_pages)
    _write_mkdocs_yml(mkdocs_yml_path, manifest.server_name, docs_dir, settings.output_dir / "site", nav)
    console.print("  [green]✓[/green] mkdocs.yml")

    # 4. Build the site
    console.print("  Running mkdocs build...")
    mkdocs_bin = Path(sys.executable).parent / "mkdocs"
    result = subprocess.run(
        [str(mkdocs_bin), "build", "--config-file", str(mkdocs_yml_path), "--quiet"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        console.print(f"  [red]mkdocs build failed:[/red]\n{result.stderr}")
    else:
        console.print(f"  [green]✓[/green] Site built → {settings.output_dir}/site/")

    return {}


_CUSTOM_CSS = """\
/* Show navigation tabs from 60em (hamburger breakpoint) upward.
   MkDocs Material hides them below 76.2344em; this restores them
   in the 60–76em range so top-level sections are always reachable. */
@media screen and (min-width: 60em) {
    .md-tabs {
        display: flex !important;
    }
}
"""


def _prepare_docs_dir(docs_dir: Path, approved_pages: list[DocPage], server_name: str) -> None:
    """Copy approved pages into the MkDocs docs directory."""
    if docs_dir.exists():
        shutil.rmtree(docs_dir)
    docs_dir.mkdir(parents=True)

    # Write each approved page
    for page in approved_pages:
        dest = docs_dir / page.spec.filename
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(page.content, encoding="utf-8")

    # MkDocs needs an index.md at the root if not present
    if not (docs_dir / "index.md").exists():
        (docs_dir / "index.md").write_text(f"# {server_name}\n\nDocumentation generated by CortexDocs.\n")

    # Custom CSS override for tab visibility
    (docs_dir / "custom.css").write_text(_CUSTOM_CSS, encoding="utf-8")


def _build_nav(doc_plan: DocPlan, approved_pages: list[DocPage]) -> list:
    """Build MkDocs nav structure from the doc plan."""
    approved_ids = {p.spec.page_id for p in approved_pages}

    nav: list = []
    tool_entries: list = []

    for spec in doc_plan.pages:
        if spec.page_id not in approved_ids:
            continue
        if spec.page_id == "overview":
            nav.insert(0, {"Overview": spec.filename})
        elif spec.page_id == "tools-index":
            # Will be nested under Tools
            tool_entries.insert(0, {"Tools Overview": spec.filename})
        elif spec.page_id.startswith("tool-"):
            tool_entries.append({spec.title: spec.filename})
        else:
            nav.append({spec.title: spec.filename})

    if tool_entries:
        nav.append({"Tools": tool_entries})

    return nav


def _write_mkdocs_yml(
    path: Path,
    server_name: str,
    docs_dir: Path,
    site_dir: Path,
    nav: list,
) -> None:
    config = {
        "site_name": f"{server_name} — MCP Documentation",
        "docs_dir": str(docs_dir.resolve()),
        "site_dir": str(site_dir.resolve()),
        "theme": {
            "name": "material",
            "palette": {"scheme": "slate", "primary": "indigo", "accent": "indigo"},
            "features": [
                "navigation.tabs",
                "navigation.sections",
                "navigation.top",
                "search.highlight",
                "content.code.copy",
            ],
        },
        "extra_css": ["custom.css"],
        "markdown_extensions": [
            "admonition",
            "pymdownx.superfences",
            "pymdownx.highlight",
            "tables",
        ],
        "nav": nav,
    }
    path.write_text(yaml.dump(config, default_flow_style=False, allow_unicode=True), encoding="utf-8")
